# Site settings
title: Matt Bayliss
email: info@mattbayliss.com
description: > # this means to ignore newlines until "baseurl:"
  Software architect by day, tinkerer by night. I also like to
  draw (pen/paper & tablet) and paint (tablet), roller skate, and
  ride motorcycles and scooters. I'm always working on too many projects
  at once.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mattbayliss.com" # the base hostname & protocol for your site
twitter_username: mattbayliss
github_username:  MattBayliss
facebook_username: MattBayliss

# Build settings
markdown: kramdown

highlighter: rouge
